---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 770922247850713090-4byV4Gjzx1oaZ5BSs0GyWWQNDC6I8oO
:access_token_secret: bkkHUsrghCTwGShUpxVe8mBw5rlEy8BGuvcHgn3CJV43U
