---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 770927087934996480-jQljcLTuuKRjDNu0BoinlXxRpSo0qHD
:access_token_secret: ZDwAJRAOAaVZcNtnhIm7Po3S4CyxC6L1o3JpFI3CKqBVw
